# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece244e48be3d26e415b5d767b38117b8636f2a6a2fe0c537f4759172a26cc998c2998068c7b80680f31ad5d9297005115b7e5d1454bb4ad2af27de01e6b2825

test:
  secret_key_base: 4bd70be6a4915b36d07a79e24fbcec2dea7c7bcf6afa3447f0aecd9c777f3a49b9c5a4424b6330601284a90f7d786e23bd037e6142a8acc8a2bcc6d017ac88ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
